services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2gb'
    networks:
      - test-network

networks:
  test-network:
    driver: bridge